- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: Fix app permissions for root uWSGI
  file:
    path: /app
    owner: root
    group: root
    mode: '644'
    recurse: yes


- name: python setup
  include_role: 
    name: common
    tasks_from: python

- name: systemd setup
  include_role: 
    name: common
    tasks_from: systemd
